### ISSUE TITLE
running humann_test with humann3

### ISSUE THREAD

**Issue by CarlaCristinaUranga** [biobakery/biobakery#10]
Hi I installed humann3 with the command:   pip install humann --no-binary :all:

Things seem to have installed ok, and the humann_test command all goes through well. However, when I try to run the demo command from the folder with the demo files, I am consistently getting the following errors:

Downloading https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AAA4XDP85WHon_eHvztxkamTa/file_list.txt?dl=1

Warning: Unable to download https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AAA4XDP85WHon_eHvztxkamTa/file_list.txt?dl=1
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/metaphlan", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/metaphlan/metaphlan.py", line 916, in main
    pars['index'] = check_and_install_database(pars['index'], pars['bowtie2db'], pars['bowtie2_build'], pars['nproc'], pars['force_download'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/metaphlan/__init__.py", line 271, in check_and_install_database
    index = resolve_latest_database(bowtie2_db, ls_f['mpa_latest'], force_redownload_latest)
UnboundLocalError: local variable 'ls_f' referenced before assignment

I verified the metaphlan is installed correctly, the command: metaphlan --version yields:

Warning! Biom python library not detected!
 Exporting to biom format will not work!
MetaPhlAn version 3.0 (20 Mar 2020)
(biobakery) curangalt-osx:humann3 curanga$ 

Please help! I really need to get this to work! Thank you!

Best,
Carla

**Comment by sunlina1995** [comment]
Hi,I met the same problem, I would like to ask you how to solve it.
(biobakery3) [caolijunamd@login07 sunlina]$  humann -i /public/home/caolijun/caolijunamd/anaconda3/envs/biobakery3/bin/humann-master/examples/demo.fastq.gz -o /public/home/caolijun/caolijunamd/anaconda3/envs/biobakery3/bin/sample_results --bowtie2 /public/home/caolijun/caolijunamd/anaconda3/bin/ --metaphlan options='--bowtie2db /public/home/caolijun/caolijunamd/anaconda3/envs/biobakery3/lib/python3.7/site-packages/metaphlan/metaphlan_databases'
Output files will be written to: /public/home/caolijun/caolijunamd/anaconda3/envs/biobakery3/bin/sample_results
Decompressing gzipped file ...


Running metaphlan ........

CRITICAL ERROR: Error executing: /public/home/caolijun/caolijunamd/anaconda3/bin/metaphlan /public/home/caolijun/caolijunamd/anaconda3/envs/biobakery3/bin/sample_results/demo_humann_temp/tmpzjh2qgkv/tmpxdhgl0i4 -t rel_ab -o /public/home/caolijun/caolijunamd/anaconda3/envs/biobakery3/bin/sample_results/demo_humann_temp/demo_metaphlan_bugs_list.tsv --input_type fastq --bowtie2out /public/home/caolijun/caolijunamd/anaconda3/envs/biobakery3/bin/sample_results/demo_humann_temp/demo_metaphlan_bowtie2.txt

Error message returned from metaphlan :

Downloading https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AAA4XDP85WHon_eHvztxkamTa/file_list.txt?dl=1

Warning: Unable to download https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AAA4XDP85WHon_eHvztxkamTa/file_list.txt?dl=1
Traceback (most recent call last):
  File "/public/home/caolijun/caolijunamd/anaconda3/bin/metaphlan", line 10, in <module>
    sys.exit(main())
  File "/public/home/caolijun/caolijunamd/anaconda3/lib/python3.8/site-packages/metaphlan/metaphlan.py", line 1187, in main
    pars['index'] = check_and_install_database(pars['index'], pars['bowtie2db'], pars['bowtie2_build'], pars['nproc'], pars['force_download'])
  File "/public/home/caolijun/caolijunamd/anaconda3/lib/python3.8/site-packages/metaphlan/metaphlan.py", line 589, in check_and_install_database
    index = resolve_latest_database(bowtie2_db, ls_f['mpa_latest'], force_redownload_latest)
UnboundLocalError: local variable 'ls_f' referenced before assignment

Please help! Thank you very much.

Best wishes to you.
