### ISSUE TITLE
extract_markers.py gives an error as following the tutorial

### ISSUE THREAD

**Issue by yilmazbah** [biobakery/biobakery#15]
Dear all, 

I have been trying to follow the tutorial in https://github.com/biobakery/biobakery/wiki/StrainPhlAn3 and in step 3 where I need to run the _extract_markers.py_ I have a problem. 

Basically it doesn't seem input files as in the tutorial. I can't run simply extract_markers.py -c s__Eubacterium_rectale -o clade_markers_. I have to run the following command instead based on when I look extract_markers.py  -h what I need to add into the command : 

_extract_markers.py  --mpa_pkl mpa_v30_CHOCOPhlAn_201901.pkl  --clade s__Eubacterium_rectale --ifn_markers biobakery_workflows_databases/strainphlan_db_markers/all_markers.fasta --ofn_markers s__Eubacterium_rectale.markers.fasta_

So basically I bring the .pkl file into the same folder where output file to see if I can run it instead calling it from databases and I used the all_markers.fasta from biobakery_workflows_databases that was installed a long time via https://bitbucket.org/biobakery/biobakery_workflows/wiki/Home.

When I run this command I got this error: 

Traceback (most recent call last):
  File "/home/ubelix/dbmr/terziev/anaconda2/bin/extract_markers.py", line 45, in <module>
    ofn_markers=args['ofn_markers'])
  File "/home/ubelix/dbmr/terziev/anaconda2/bin/extract_markers.py", line 27, in extract_markers
    db = pickle.loads(bz2.decompress(ifile.read()))
  File "/home/ubelix/dbmr/terziev/anaconda2/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/home/ubelix/dbmr/terziev/anaconda2/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/home/ubelix/dbmr/terziev/anaconda2/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 3

Any idea what is going on here? I really I can't figure it out.

Thank you so much for your all help. Looking forward to hear your suggestions.

Best wishes
Bahti

**Comment by yilmazbah** [comment]
My bad... I figured it out. Phyton2 was running and when I did with Phyton3 problem solved. Sorry for generating issue here.
