### ISSUE TITLE
metaphlan3 Error: UnboundLocalError: local variable 'ls_f' referenced before assignment

### ISSUE THREAD

**Issue by BoyanZhou** [biobakery/biobakery#16]
I had an error when running metaphlan3 in the first step.
My command is "metaphlan SRR7563636_1.fastq,SRR7563636_2.fastq --input_type fastq -s sams/SRR7563636.sam.bz2 --bowtie2out bowtie2/SRR7563636.bowtie2.bz2 -o profiles/SRR7563636_profile.tsv". 

But it reported,
Downloading https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AAA4XDP85WHon_eHvztxkamTa/file_list.txt?dl=1

Warning: Unable to download https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AAA4XDP85WHon_eHvztxkamTa/file_list.txt?dl=1
Traceback (most recent call last):
  File "/gpfs/share/apps/python/cpu/3.6.5/bin/metaphlan", line 8, in <module>
    sys.exit(main())
  File "/gpfs/share/apps/python/cpu/3.6.5/lib/python3.6/site-packages/metaphlan/metaphlan.py", line 916, in main
    pars['index'] = check_and_install_database(pars['index'], pars['bowtie2db'], pars['bowtie2_build'], pars['nproc'], pars['force_download'])
  File "/gpfs/share/apps/python/cpu/3.6.5/lib/python3.6/site-packages/metaphlan/__init__.py", line 271, in check_and_install_database
    index = resolve_latest_database(bowtie2_db, ls_f['mpa_latest'], force_redownload_latest)
UnboundLocalError: local variable 'ls_f' referenced before assignment

Is there any way to solve or bypass this problem? Thank you so much!

**Comment by xushaoyi** [comment]
I have the same problem when I used metaphlan2, did you solve it? hope for your reply
here is the details:
Warning: Unable to download https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AAA4XDP85WHon_eHvztxkamTa/file_list.txt?dl=1
Traceback (most recent call last):
  File "/public/home/lizhen/lib/anaconda3/envs/metaphlan2/bin/metaphlan2.py", line 1574, in <module>
    metaphlan2()
  File "/public/home/lizhen/lib/anaconda3/envs/metaphlan2/bin/metaphlan2.py", line 1367, in metaphlan2
    check_and_install_database(pars['index'], pars['bowtie2db'], pars['bowtie2_build'], pars['nproc'])
  File "/public/home/lizhen/lib/anaconda3/envs/metaphlan2/bin/metaphlan2.py", line 836, in check_and_install_database
    download_unpack_tar(FILE_LIST, index, bowtie2_db, bowtie2_build, nproc)
  File "/public/home/lizhen/lib/anaconda3/envs/metaphlan2/bin/metaphlan2.py", line 745, in download_unpack_tar
    url_tar_file = ls_f["mpa_" + download_file_name + ".tar"]
UnboundLocalError: local variable 'ls_f' referenced before assignment

**Comment by Wenping1975** [comment]
Sorry, I did not fix the problem.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "biobakery/biobakery"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月21日(星期二) 晚上10:13
收件人:&nbsp;"biobakery/biobakery"<biobakery@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [biobakery/biobakery] metaphlan3 Error: UnboundLocalError: local variable 'ls_f' referenced before assignment (#16)





 
I have the same problem when I used metaphlan2, did you solve it? hope for your reply
 here is the details:
 Warning: Unable to download https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AAA4XDP85WHon_eHvztxkamTa/file_list.txt?dl=1
 Traceback (most recent call last):
 File "/public/home/lizhen/lib/anaconda3/envs/metaphlan2/bin/metaphlan2.py", line 1574, in 
 metaphlan2()
 File "/public/home/lizhen/lib/anaconda3/envs/metaphlan2/bin/metaphlan2.py", line 1367, in metaphlan2
 check_and_install_database(pars['index'], pars['bowtie2db'], pars['bowtie2_build'], pars['nproc'])
 File "/public/home/lizhen/lib/anaconda3/envs/metaphlan2/bin/metaphlan2.py", line 836, in check_and_install_database
 download_unpack_tar(FILE_LIST, index, bowtie2_db, bowtie2_build, nproc)
 File "/public/home/lizhen/lib/anaconda3/envs/metaphlan2/bin/metaphlan2.py", line 745, in download_unpack_tar
 url_tar_file = ls_f["mpa_" + download_file_name + ".tar"]
 UnboundLocalError: local variable 'ls_f' referenced before assignment

**Comment by luoboqingcai81** [comment]
The same issue， i found it maybe Internet problem，and i download the metaphlan_databases to the local , but is useless , i don't known whether i  need other steps

**Comment by luoboqingcai81** [comment]
The same issue， i found it maybe Internet problem，and i download the metaphlan_databases to the local , but is useless , i don't known whether i need other steps (bowtie2-build mpa_v30_CHOCOPhlAn_201901.fna mpa_v30_CHOCOPhlAn_201901   )(/home/xujianjun/anaconda3/envs/metahumann3/lib/python3.7/site-packages/metaphlan/metaphlan_databases)

**Comment by Wenping1975** [comment]
run the code like this:


$metaphlan metagenome.sam --input_type sam -o profiled_metagenome.txt -x mpa_v30_CHOCOPhlAn_201901 --bowtie2db /data/xmjd/miniconda2/envs/py37/lib/python3.7/site-packages/metaphlan/metaphlan_databases/







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "biobakery/biobakery"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月24日(星期五) 下午5:14
收件人:&nbsp;"biobakery/biobakery"<biobakery@noreply.github.com&gt;;
抄送:&nbsp;"友缘人"<357009250@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [biobakery/biobakery] metaphlan3 Error: UnboundLocalError: local variable 'ls_f' referenced before assignment (#16)





 
The same issue， i found it maybe Internet problem，and i download the metaphlan_databases to the local , but is useless , i don't known whether i need other steps (bowtie2-build mpa_v30_CHOCOPhlAn_201901.fna mpa_v30_CHOCOPhlAn_201901   )(/home/xujianjun/anaconda3/envs/metahumann3/lib/python3.7/site-packages/metaphlan/metaphlan_databases)

**Comment by xiaoli-HIT** [comment]
Thanks for the comment from Wenping1975. I have solved this issue by you comment!

**Comment by kullrich** [comment]
Metaphlan4 error:

Same problem here, could you please more clearly explain, how the manual downloaded database can be used.

After downloading the manual database it is not clear, if it needs to be unpacked and if the subfolder of the bowtie2 index needs to be downloaded at all.

Thank you in anticipation

**Comment by nishu92** [comment]
In output file of Metaphlan 3.0 i am getting as below:
#mpa_v30_CHOCOPhlAn_201901
#/mstore/compute/users/sudhir/.conda/envs/metaphlan/bin/metaphlan /mstore/compute/users/sudhir/Forest/Trim/A1_R1.trim.fastq.gz,/mstore/compute/users/sudhir/Forest/Trim/A1_R2.trim.fastq.gz --input_type fastq --bowtie2out /mstore/compute/users/sudhir/Forest/Trim/ReadLib/A1.bowtie2.bz2 --nproc 50 -o /mstore/compute/users/sudhir/Forest/Trim/ReadLib/Profiled_A1.text -x mpa_v30_CHOCOPhlAn_201901 --bowtie2db /mstore/compute/users/sudhir/backup/MetaPhlAn
#SampleID	Metaphlan_Analysis
#clade_name	NCBI_tax_id	relative_abundance
UNKNOWN	-1	100.0


my script is 
metaphlan /mstore/compute/users/sudhir/Forest/Trim/A1_R1.trim.fastq.gz,/mstore/compute/users/sudhir/Forest/Trim/A1_R2.trim.fastq.gz --input_type fastq --bowtie2out /mstore/compute/users/sudhir/Forest/Trim/ReadLib/A1.bowtie2.bz2 --nproc 50 -o /mstore/compute/users/sudhir/Forest/Trim/ReadLib/Profiled_A1.text -x mpa_v30_CHOCOPhlAn_201901 --bowtie2db /mstore/compute/users/sudhir/backup/MetaPhlAn

pl. help

**Comment by tanxirong** [comment]
> run the code like this: $metaphlan metagenome.sam --input_type sam -o profiled_metagenome.txt -x mpa_v30_CHOCOPhlAn_201901 --bowtie2db /data/xmjd/miniconda2/envs/py37/lib/python3.7/site-packages/metaphlan/metaphlan_databases/
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "biobakery/biobakery" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月24日(星期五) 下午5:14 收件人:&nbsp;"biobakery/biobakery"<biobakery@noreply.github.com&gt;; 抄送:&nbsp;"友缘人"<357009250@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [biobakery/biobakery] metaphlan3 Error: UnboundLocalError: local variable 'ls_f' referenced before assignment (#16) The same issue， i found it maybe Internet problem，and i download the metaphlan_databases to the local , but is useless , i don't known whether i need other steps (bowtie2-build mpa_v30_CHOCOPhlAn_201901.fna mpa_v30_CHOCOPhlAn_201901 )(/home/xujianjun/anaconda3/envs/metahumann3/lib/python3.7/site-packages/metaphlan/metaphlan_databases) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
Could I know how you deal with it indetal? Thanks a lot.
