### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Caelyn996** [biobakery/biobakery#24]
Hi,
When I used the code "metaphlan e1_1.fastq,e1_2.fastq --bowtie2out e1.bowtie2.bz2 --nproc 6 --bowtie2db ~/database/metaphlan_databases/ -x mpa_v30_CHOCOPhlAn_201901 --input_type fastq -o e1_profiled.txt" to run metaphlan 3.0.5, I got the error below. Is there anyone who know how to fix it? Thanks so much!

Traceback (most recent call last):
File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/bin/metaphlan", line 10, in 
sys.exit(main())
File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 1072, in main
pars['tax_lev']+"__" if pars['tax_lev'] != 'a' else None )
File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 739, in relative_abundances
tot_ab += clade.compute_abundance()
File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in compute_abundance
sum_ab = sum([c.compute_abundance() for c in self.children.values()])
File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in 
sum_ab = sum([c.compute_abundance() for c in self.children.values()])
File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in compute_abundance
sum_ab = sum([c.compute_abundance() for c in self.children.values()])
File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in 
sum_ab = sum([c.compute_abundance() for c in self.children.values()])
File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in compute_abundance
sum_ab = sum([c.compute_abundance() for c in self.children.values()])
File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in 
sum_ab = sum([c.compute_abundance() for c in self.children.values()])
File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in compute_abundance
sum_ab = sum([c.compute_abundance() for c in self.children.values()])
File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in 
sum_ab = sum([c.compute_abundance() for c in self.children.values()])
File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in compute_abundance
sum_ab = sum([c.compute_abundance() for c in self.children.values()])
File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in 
sum_ab = sum([c.compute_abundance() for c in self.children.values()])
File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in compute_abundance
sum_ab = sum([c.compute_abundance() for c in self.children.values()])
File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in 
sum_ab = sum([c.compute_abundance() for c in self.children.values()])
File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 589, in compute_abundance
wnreads = sorted([(float(n)/(r-self.avg_read_length+1),(r - self.avg_read_length+1) ,n) for r,n in rat_nreads], key=lambda x:x[0])
File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 589, in 
wnreads = sorted([(float(n)/(r-self.avg_read_length+1),(r - self.avg_read_length+1) ,n) for r,n in rat_nreads], key=lambda x:x[0])
ZeroDivisionError: float division by zero

**Comment by Caelyn996** [comment]
It has already been solved. Metaphlan 3.0.6 will be fine.
