### ISSUE TITLE
Run terminated with process error

### ISSUE THREAD

**Issue by 18AS** [biobakery/biobakery#28]
I was trying to run humann3. I am getting the below mentioned error. Can someone please help me understand this and sort it?

 humann --input 4_host_removed_paired.fastq.gz --output H3_4_host_rem_paired_2
Creating output directory: /home/others/bioinfo/AGPS/4/H3_4_host_rem_paired_2
Output files will be written to: /home/others/bioinfo/AGPS/4/H3_4_host_rem_paired_2
Decompressing gzipped file ...

Removing spaces from identifiers in input file ...

WARNING: Can not call software version for bowtie2

Running metaphlan ........

CRITICAL ERROR: Error executing: /home/others/bioinfo/anaconda2/envs/H4/bin/metaphlan /home/others/bioinfo/AGPS/4/H3_4_host_rem_paired_2/4_host_removed_paired_humann_temp/tmpm08acptp/tmp71er6ey3 -t rel_ab -o /home/others/bioinfo/AGPS/4/H3_4_host_rem_paired_2/4_host_removed_paired_humann_temp/4_host_removed_paired_metaphlan_bugs_list.tsv --input_type fastq --bowtie2out /home/others/bioinfo/AGPS/4/H3_4_host_rem_paired_2/4_host_removed_paired_humann_temp/4_host_removed_paired_metaphlan_bowtie2.txt

Error message returned from metaphlan :

Downloading http://cmprod1.cibio.unitn.it/biobakery3/metaphlan_databases/mpa_latest
Downloading file of size: 0.00 MB
0.01 MB 31507.69 %  71.55 MB/sec  0 min -0 sec
Downloading MetaPhlAn database
Please note due to the size this might take a few minutes

Downloading http://cmprod1.cibio.unitn.it/biobakery3/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901.tar
Downloading file of size: 366.62 MB
366.62 MB 100.00 %   1.17 MB/sec  0 min -0 sec
Downloading http://cmprod1.cibio.unitn.it/biobakery3/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901.md5
Downloading file of size: 0.00 MB
0.01 MB 12800.00 %  67.70 MB/sec  0 min -0 sec

Decompressing /home/others/bioinfo/anaconda2/envs/H4/lib/python3.7/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901.fna.bz2 into /home/others/bioinfo/anaconda2/envs/H4/lib/python3.7/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901.fna
Traceback (most recent call last):
  File "/home/others/bioinfo/anaconda2/envs/H4/bin/metaphlan", line 10, in <module>
    sys.exit(main())
  File "/home/others/bioinfo/anaconda2/envs/H4/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 925, in main
    pars['index'] = check_and_install_database(pars['index'], pars['bowtie2db'], pars['bowtie2_build'], pars['nproc'], pars['force_download'])
  File "/home/others/bioinfo/anaconda2/envs/H4/lib/python3.7/site-packages/metaphlan/__init__.py", line 301, in check_and_install_database
    download_unpack_tar(index, bowtie2_db, bowtie2_build, nproc, use_zenodo)
  File "/home/others/bioinfo/anaconda2/envs/H4/lib/python3.7/site-packages/metaphlan/__init__.py", line 180, in download_unpack_tar
    bt2_build_output = subp.check_output([bowtie2_build, '--usage'], stderr=subp.STDOUT)
  File "/home/others/bioinfo/anaconda2/envs/H4/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/others/bioinfo/anaconda2/envs/H4/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bowtie2-build', '--usage']' returned non-zero exit status 127.

**Comment by KJ-Ma** [comment]
have you solved it? I also meet with this problem.
