### ISSUE TITLE
Strainphlan.py: TypeError: unpackb() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by tamburinif** [biobakery/biobakery#3]
Hi there,

I'm getting the following error when I try to run strainphlan.py to identify clades in my samples:
`TypeError: unpackb() got an unexpected keyword argument 'encoding'`

Command:
```strainphlan.py \
--ifn_samples sample_markers/S18072001090/S18072001090.markers sample_markers/S18072001185/S18072001185.markers \
--output_dir . \
--print_clades_only \
--nprocs_main 8 \
--mpa_pkl /gstore/home/tamburif/miniconda3/envs/meta
phlan2/bin/metaphlan_databases/mpa_v296_CHOCOPhlAn_201901.pkl \
> clades.txt
```

Any help is appreciated!

Full details:

```
2020-03-31 21:13:28,845 | INFO | __main__ | strainer | 1364 | Load mpa_pkl
2020-03-31 21:13:38,784 | INFO | __main__ | strainer | 1380 | Get clades from db
2020-03-31 21:13:40,299 | INFO | __main__ | strainer | 1425 | Get clades from samples
2020-03-31 21:13:40,403 | DEBUG | __main__ | load_sample | 1150 | load sample_markers/S18072001090/S18072001090.markers
2020-03-31 21:13:40,403 | DEBUG | __main__ | load_sample | 1150 | load sample_markers/S18072001185/S18072001185.markers
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/gstore/home/tamburif/miniconda3/envs/metaphlan2/bin/ooSubprocess.py", line 246, in wrapper
    return f(*args, **kwargs)
  File "/gstore/home/tamburif/miniconda3/envs/metaphlan2/bin/strainphlan.py", line 1162, in load_sample
    marker2seq = msgpack.unpack(ifile, use_list=False, encoding='utf-8')
  File "/gstore/home/tamburif/miniconda3/envs/metaphlan2/lib/python3.6/site-packages/msgpack/__init__.py", line 46, in unpack
    return unpackb(data, **kwargs)
  File "msgpack/_unpacker.pyx", line 144, in msgpack._cmsgpack.unpackb
TypeError: unpackb() got an unexpected keyword argument 'encoding'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gstore/home/tamburif/miniconda3/envs/metaphlan2/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/gstore/home/tamburif/miniconda3/envs/metaphlan2/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/gstore/home/tamburif/miniconda3/envs/metaphlan2/bin/ooSubprocess.py", line 250, in wrapper
    raise Exception(traceback.format_exc())
Exception: Traceback (most recent call last):
  File "/gstore/home/tamburif/miniconda3/envs/metaphlan2/bin/ooSubprocess.py", line 246, in wrapper
    return f(*args, **kwargs)
  File "/gstore/home/tamburif/miniconda3/envs/metaphlan2/bin/strainphlan.py", line 1162, in load_sample
    marker2seq = msgpack.unpack(ifile, use_list=False, encoding='utf-8')
  File "/gstore/home/tamburif/miniconda3/envs/metaphlan2/lib/python3.6/site-packages/msgpack/__init__.py", line 46, in unpack
    return unpackb(data, **kwargs)
  File "msgpack/_unpacker.pyx", line 144, in msgpack._cmsgpack.unpackb
TypeError: unpackb() got an unexpected keyword argument 'encoding'

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gstore/home/tamburif/miniconda3/envs/metaphlan2/bin/strainphlan.py", line 1585, in <module>
    strainphlan()
  File "/gstore/home/tamburif/miniconda3/envs/metaphlan2/bin/strainphlan.py", line 1581, in strainphlan
    strainer(args)
  File "/gstore/home/tamburif/miniconda3/envs/metaphlan2/bin/strainphlan.py", line 1429, in strainer
    kept_markers=kept_markers)
  File "/gstore/home/tamburif/miniconda3/envs/metaphlan2/bin/strainphlan.py", line 1272, in load_all_samples
    use_threads=args['use_threads'])
  File "/gstore/home/tamburif/miniconda3/envs/metaphlan2/bin/ooSubprocess.py", line 260, in parallelize
    results = pool.map(func, args)
  File "/gstore/home/tamburif/miniconda3/envs/metaphlan2/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/gstore/home/tamburif/miniconda3/envs/metaphlan2/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
Exception: Traceback (most recent call last):
  File "/gstore/home/tamburif/miniconda3/envs/metaphlan2/bin/ooSubprocess.py", line 246, in wrapper
    return f(*args, **kwargs)
  File "/gstore/home/tamburif/miniconda3/envs/metaphlan2/bin/strainphlan.py", line 1162, in load_sample
    marker2seq = msgpack.unpack(ifile, use_list=False, encoding='utf-8')
  File "/gstore/home/tamburif/miniconda3/envs/metaphlan2/lib/python3.6/site-packages/msgpack/__init__.py", line 46, in unpack
    return unpackb(data, **kwargs)
  File "msgpack/_unpacker.pyx", line 144, in msgpack._cmsgpack.unpackb
TypeError: unpackb() got an unexpected keyword argument 'encoding'
```

**Comment by tamburinif** [comment]
Should add that I am using the latest conda version as of today (March 31 2020)

I was able to fix this issue by downgrading msgpack to v0.6.2

`pip install msgpack==0.6.2`

**Comment by payala** [comment]
encoding kwarg was deprecated and has now been removed. If you have access to the code, it looks like you should replace the `encoding="..."` keyword argument with `raw=False`.

More details here:
https://github.com/msgpack/msgpack-python/pull/380/commits/a3c9bee23de31b0f7fb7cb55f1e0e917f1486251

**Comment by RongSong1993** [comment]
@tamburinif thaks a lot, it works for me。
