### ISSUE TITLE
ModuleNotFoundError: No module named 'leveldb'

### ISSUE THREAD

**Issue by imonteroo** [biobakery/biobakery#35]
Hello:

I am trying to install biobakery workflos databases but y receive this error, despite I have istalled leveldb by "pip install leveldb"

``$ biobakery_workflows_databases --install wmgx_demo
Traceback (most recent call last):
  File "/home/microviable/anaconda3/envs/metaphlan/bin/biobakery_workflows_databases", line 6, in <module>
    from biobakery_workflows.biobakery_workflows_databases import main
  File "/home/microviable/anaconda3/envs/metaphlan/lib/python3.7/site-packages/biobakery_workflows/biobakery_workflows_databases.py", line 30, in <module>
    from . import utilities
  File "/home/microviable/anaconda3/envs/metaphlan/lib/python3.7/site-packages/biobakery_workflows/utilities.py", line 34, in <module>
    from anadama2.tracked import TrackedDirectory
  File "/home/microviable/anaconda3/envs/metaphlan/lib/python3.7/site-packages/anadama2/__init__.py", line 83, in <module>
    from .workflow import Workflow
  File "/home/microviable/anaconda3/envs/metaphlan/lib/python3.7/site-packages/anadama2/workflow.py", line 24, in <module>
    from . import backends
  File "/home/microviable/anaconda3/envs/metaphlan/lib/python3.7/site-packages/anadama2/backends.py", line 7, in <module>
    import leveldb
ModuleNotFoundError: No module named 'leveldb'"

**Comment by BITsmyoon** [comment]
I had the same problem
I solved it with

conda install -c conda-forge python-leveldb

good luck
