### ISSUE TITLE
Warning: Unable to download https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AAA4XDP85WHon_eHvztxkamTa/file_list.txt?dl=1

### ISSUE THREAD

**Issue by HKathy33** [biobakery/biobakery#37]
Hi, I want to try the command metaphlan *.fastq --inputtype fastq > *.txt. But this warning appeared and I can't open the appeared pages.

Downloading https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AAA4XDP85WHon_eHvztxkamTa/file_list.txt?dl=1

Warning: Unable to download https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AAA4XDP85WHon_eHvztxkamTa/file_list.txt?dl=1
Traceback (most recent call last):
  File "/home/fansih/anaconda3/envs/biobakery-workflow/bin/metaphlan", line 10, in <module>
    sys.exit(main())
  File "/home/fansih/anaconda3/envs/biobakery-workflow/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 1187, in main
    pars['index'] = check_and_install_database(pars['index'], pars['bowtie2db'], pars['bowtie2_build'], pars['nproc'], pars['force_download'])
  File "/home/fansih/anaconda3/envs/biobakery-workflow/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 589, in check_and_install_database
    index = resolve_latest_database(bowtie2_db, ls_f['mpa_latest'], force_redownload_latest)
UnboundLocalError: local variable 'ls_f' referenced before assignment

**Comment by emrahkirdok** [comment]
Hi, I have the same issue. Is there any updates on this yet? Thank you.

**Comment by Fightjiang** [comment]
I also have the same issue . Are you solve this problem? Could you help me? Thank you.
