### ISSUE TITLE
Error in profiling a single metagenome from raw reads

### ISSUE THREAD

**Issue by sjtu-piaopiao** [biobakery/biobakery#39]
Hi,
I'm new to metaphlan, and trying to run the tutorial. But there was a problem with the first step.
Code: metaphlan SRS014476-Supragingival_plaque.fasta.gz --input_type fasta -o SRS014476-Supragingival_plaque_profile.txt
Output:
Warning! Biom python library not detected!
Exporting to biom format will not work!
Downloading MetaPhlAn database
Please note due to the size this might take a few minutes
File /lustre/home/acct-clslt/clslt-pp/.conda/envs/mpa/lib/python3.7/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901.tar already present!
File /lustre/home/acct-clslt/clslt-pp/.conda/envs/mpa/lib/python3.7/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901.md5 already present!
Traceback (most recent call last):
  File "/lustre/home/acct-clslt/clslt-pp/.conda/envs/mpa/bin/metaphlan", line 10, in <module>
    sys.exit(main())
  File "/lustre/home/acct-clslt/clslt-pp/.conda/envs/mpa/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 985, in main
    pars['index'] = check_and_install_database(pars['index'], pars['bowtie2db'], pars['bowtie2_build'], pars['nproc'], pars['force_download'])
  File "/lustre/home/acct-clslt/clslt-pp/.conda/envs/mpa/lib/python3.7/site-packages/metaphlan/__init__.py", line 304, in check_and_install_database
    download_unpack_tar(index, bowtie2_db, bowtie2_build, nproc, use_zenodo)
  File "/lustre/home/acct-clslt/clslt-pp/.conda/envs/mpa/lib/python3.7/site-packages/metaphlan/__init__.py", line 180, in download_unpack_tar
    bt2_build_output = subp.check_output([bowtie2_build, '--usage'], stderr=subp.STDOUT)
  File "/lustre/home/acct-clslt/clslt-pp/.conda/envs/mpa/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/lustre/home/acct-clslt/clslt-pp/.conda/envs/mpa/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bowtie2-build', '--usage']' returned non-zero exit status 127.

How can I solve this problem?

**Comment by kescobo** [comment]
Hi there! You may want to ask in the forums to get a quicker response: https://forum.biobakery.org/
