### ISSUE TITLE
ERROR: Unable to create folder for database install

### ISSUE THREAD

**Issue by jaquol** [biobakery/biobakery#4]
I am trying to run biobakery workflows (Python: 2.7.15; wgmx.py: v0.1) on a shared deployment (app tree) model.

When I run the following command locally:
``
INPUT=/mnt/efs/home/dmb6464/projects/sparc/data/test_small
OUTPUT=/mnt/efs/home/dmb6464/projects/sparc/results/test_small
DATABASES=/mnt/efs/home/dmb6464/biobakery_workflows_databases
biobakery_workflows wmgx --input $INPUT –output $OUTPUT --contaminate-databases $DATABASES --remove-intermediate-output --log-level DEBUG --quit-early
``

The output is:
``
(Apr 09 10:17:44) [ 1/57 -   1.75%] **Skipped  ** Task  3: kneaddata____A999BJ776-001_MQ2273_WGS_copy_R2
(Apr 09 10:17:44) [ 1/57 -   1.75%] **Ready    ** Task 12: metaphlan2____A999BJ776-001_MQ2273_WGS_copy_R2
(Apr 09 10:17:44) [ 1/57 -   1.75%] **Started  ** Task 12: metaphlan2____A999BJ776-001_MQ2273_WGS_copy_R2
(Apr 09 10:17:53) [ 2/57 -   3.51%] **Failed   ** Task 12: metaphlan2____A999BJ776-001_MQ2273_WGS_copy_R2
Run Finished
Task 12 failed
  Name: metaphlan2____A999BJ776-001_MQ2273_WGS_copy_R2
  Original error:
  Error executing action 0. Original Exception:
  Traceback (most recent call last):
    File "/insight/app/python/v2.7.15/lib/python2.7/site-packages/anadama2/runners.py", line 197, in _run_task_locally
      action_func(task)
    File "/insight/app/python/v2.7.15/lib/python2.7/site-packages/anadama2/helpers.py", line 77, in actually_sh
     ret = _sh(s, **kwargs)
    File "/insight/app/python/v2.7.15/lib/python2.7/site-packages/anadama2/util/__init__.py", line 319, in sh
      raise ShellException(proc.returncode, msg.format(cmd, ret[0], ret[1]))
  ShellException: [Errno 1] Command `metaphlan2.py /mnt/efs/home/dmb6464/projects/sparc/results/test_small/kneaddata/main/A999BJ776-001_MQ2273_WGS_copy_R2.fastq --input_type fastq --output_file /mnt/efs/home/dmb6464/projects/sparc/results/test_small/metaphlan2/main/A999BJ776-001_MQ2273_WGS_copy_R2_taxonomic_profile.tsv --samout /mnt/efs/home/dmb6464/projects/sparc/results/test_small/metaphlan2/main/A999BJ776-001_MQ2273_WGS_copy_R2_bowtie2.sam --nproc 1 --no_map --tmp_dir /mnt/efs/home/dmb6464/projects/sparc/results/test_small/metaphlan2/main' failed.
  Out:
  Err: Warning! Biom python library not detected!
   Exporting to biom format will not work!
 
  Downloading MetaPhlAn2 database
  Please note due to the size this might take a few minutes
  **ERROR: Unable to create folder for database install: /insight/app/python/v2.7.15/bin/metaphlan_databases**
 
 
Traceback (most recent call last):
  File "/insight/app/python/v2.7.15/bin/wmgx.py", line 92, in <module>
    workflow.go()
  File "/insight/app/python/v2.7.15/lib/python2.7/site-packages/anadama2/workflow.py", line 740, in go
    self._handle_finished()
  File "/insight/app/python/v2.7.15/lib/python2.7/site-packages/anadama2/workflow.py", line 772, in _handle_finished
    raise RunFailed()
anadama2.workflow.RunFailed
``

I highlighted in bold above what I think the problem is:

1. biobakery_workflows wgmx looks for the metaphlan databases in /insight/app/python/v2.7.15/bin/ but those are not found there because they are at /mnt/efs/home/dmb6464/biobakery_workflows_databases

2. iobakery_workflows wgmx tries to install them and write them to /insight/app/python/v2.7.15/bin/metaphlan_databases but I guess that my user does not have writing permissions in that directory
Obviously, the system administrators could make that directory writable for all users but this is far from optimal because each user would not have control of the databases that are used in each run of the software.

Is there any way to specify biobakery_workflows wgmx the path where the databases are?

**Comment by ljmciver** [comment]
Hello @jaquol , Thank you for the detailed post!

You can set the location of the workflows databases with a single environment variable or with a variable for each database. See the user manual for more information: https://github.com/biobakery/biobakery_workflows . With your example you would change `$DATABASES` to `$BIOBAKERY_WORKFLOWS_DATABASES`. However, this is only for the databases that are flexible in their install paths (kneaddata, humann2, strainphlan and greengenes). 

Metaphlan always tries to install its database in the same folder as the executable. We don't currently have a way to change this and I realize that is inconvenient with respect to system permissions. This is done in part because the database is tied to a specific software version. Could you possibly install metaphlan in a different location, one which you have write permissions to the folder? If so this would resolve the issue you are seeing. Alternatively if you would ask your system admins to run the metaphlan command once to install the databases this would also resolve your issue as the databases are only installed once (with the first execution) and then are used for future runs.

Thanks again for the detailed post and please respond with questions/issues!

Thanks!
Lauren
