### ISSUE TITLE
Docker is missing dependencies missing for 16S workflow 

### ISSUE THREAD

**Issue by jason-weirather** [biobakery/biobakery#5]
Trying to execute the 16s workflow via docker.  From the documentation it sounded like only `usearch` would be missing due to its licensing issues, however it seems that `vsearch` is also excluded from the docker.  I didn't see any commands  to enable it.  Furthermore it seems like the documentation has not kept up with the docker or vice versa , there is no option for `16S` when downloading the database.

Error for trying to use `vsearch`:

```
I have no name!@1dd3bc3dcc38:/homes6/jasonw/LocalWork/test$ biobakery_workflows 16s --input $(pwd)/data --output $(pwd)/output_data --method vsearch
Traceback (most recent call last):
  File "/usr/local/bin/16s.py", line 156, in <module>
    workflow, args.method, demultiplexed_files, args.input_extension, args.output, args.pair_identifier, args.threads)
  File "/usr/local/lib/python2.7/dist-packages/biobakery_workflows/tasks/sixteen_s.py", line 86, in merge_samples_and_rename
    renamed_files = merge_pairs_and_rename(workflow, method, input_files, extension, output_folder, pair_identifier, threads)
  File "/usr/local/lib/python2.7/dist-packages/biobakery_workflows/tasks/sixteen_s.py", line 181, in merge_pairs_and_rename
    depends=[read1, read2, TrackedExecutable("vsearch")],
  File "/usr/local/lib/python2.7/dist-packages/anadama2/tracked.py", line 199, in __new__
    real_key = cls.key(key)
  File "/usr/local/lib/python2.7/dist-packages/anadama2/tracked.py", line 690, in key
    "Unable to find binary or script `{}'".format(name))
ValueError: Unable to find binary or script `vsearch'
```

Error for trying to download the database (using the command from the instructions):

```
I have no name!@1dd3bc3dcc38:/homes6/jasonw/LocalWork/test$ biobakery_workflows_databases --install 16s
usage: biobakery_workflows_databases [-h] [--available] [--install <workflow>]
                                     [--location LOCATION]
biobakery_workflows_databases: error: argument --install: invalid choice: '16s' (choose from 'wmgx', 'wmgx_demo', 'wmgx_wmtx', '16s_usearch', '16s_dada2', '16s_its', 'isolate_assembly')
```

These were executed using docker version `0.14.3_cloud` from the biobakery dockerhub.  If there is a version of this docker you recommend that pairs to the tutorial documentation when it was generated could you please let me know?  If docker is not supported for the 16s workflow can you please let me know your recommended method of accessing the workflow.

**Comment by ljmciver** [comment]
Hello @jason-weirather , Sorry you are having issues using the docker image. Please try a non-"cloud" version image as those have a limited number of dependencies installed. They are currently for our internal testing to see the disk space reduction for moving away from conda in docker. 

The workflow databases are available there are just multiple methods for 16s. Depending on the option you will use select: 16s_usearch, 16s_data2, or 16s_its.

Thank you!
Lauren

**Comment by jason-weirather** [comment]
Hi @ljmciver , thanks for the response, and for making these well documented workflows.  

I have been able to run the 16s pipeline (without the follow-up visualization command) by building an execution environment for it and following the instructions in the documentation.  I've containerized that in a docker/wdl pipeline here:

https://github.com/jason-weirather/cio-wdl-16s-microbiome

I'm satisfied with running your pipeline in our container, but I'm also glad to try your container or adjusting how we run according to your recommendation. 

The cloud tag `biobakery/workflows:0.13.2` looks like it progressed farther and produced most of the outputs (from the 16s command), however it did encounter errors and appears like a some files like .biom are missing. 

Prior to execution I set the environment variables in the docker container:

```
export GREEN_GENES_USEARCH_DB="/homes6/jasonw/LocalWork/test/DB/97_otus.fasta"
export GREEN_GENES_FASTA_DB="/homes6/jasonw/LocalWork/test/DB/97_otus.fasta"
export GREEN_GENES_TAXONOMY_DB="/homes6/jasonw/LocalWork/test/DB/97_otu_taxonomy.txt"
```

And I executed the command in the container
`$ biobakery_workflows 16s --input data2 --output output_data --method vsearch`

Which produced the following error

```
Name: biom
  Original error: 
  Error executing action 0. Original Exception: 
  Traceback (most recent call last):
    File "/opt/conda/lib/python2.7/site-packages/anadama2/runners.py", line 201, in _run_task_locally
      action_func(task)
    File "/opt/conda/lib/python2.7/site-packages/anadama2/helpers.py", line 84, in actually_sh
      ret = _sh(s, **kwargs)
    File "/opt/conda/lib/python2.7/site-packages/anadama2/util/__init__.py", line 320, in sh
      raise ShellException(proc.returncode, msg.format(cmd, ret[0], ret[1]))
  ShellException: [Errno 1] Command `remove_if_exists.py /homes6/jasonw/LocalWork/test/output_data/all_samples_taxonomy_closed_reference.biom ; biom convert -i /homes6/jasonw/LocalWork/test/output_data/all_samples_taxonomy_closed_reference.tsv -o /homes6/jasonw/LocalWork/test/output_data/all_samples_taxonomy_closed_reference.biom --table-type='OTU table' --to-json --process-obs-metadata=taxonomy --output-metadata-id=taxonomy' failed. 
  Out: 
  Err: Traceback (most recent call last):
    File "/opt/conda/bin/biom", line 11, in <module>
      sys.exit(cli())
    File "/opt/conda/lib/python2.7/site-packages/click/core.py", line 764, in __call__
      return self.main(*args, **kwargs)
    File "/opt/conda/lib/python2.7/site-packages/click/core.py", line 717, in main
      rv = self.invoke(ctx)
    File "/opt/conda/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/opt/conda/lib/python2.7/site-packages/click/core.py", line 956, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/opt/conda/lib/python2.7/site-packages/click/core.py", line 555, in invoke
      return callback(*args, **kwargs)
    File "/opt/conda/lib/python2.7/site-packages/biom/cli/table_converter.py", line 114, in convert
      table = load_table(input_fp)
    File "/opt/conda/lib/python2.7/site-packages/biom/parse.py", line 660, in load_table
      table = parse_biom_table(fp)
    File "/opt/conda/lib/python2.7/site-packages/biom/parse.py", line 412, in parse_biom_table
      t = Table.from_tsv(fp, None, None, lambda x: x)
    File "/opt/conda/lib/python2.7/site-packages/biom/table.py", line 4631, in from_tsv
      t_md_name) = Table._extract_data_from_tsv(lines, **kwargs)
    File "/opt/conda/lib/python2.7/site-packages/biom/table.py", line 4722, in _extract_data_from_tsv
      for index in range(0, data_start + 1):
  UnboundLocalError: local variable 'data_start' referenced before assignment
```

**Comment by ljmciver** [comment]
Hi @jason-weirather , Thanks for the detailed post! Try rolling back to biom_format v2.1.5. I think that will resolve the error you are seeing.

Thanks,
Lauren
